apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: jwt-key-volume
          {{- if .Values.pykubeslurm.jwtKeyFromSecret }}
          secret:
            secretName: {{ .Values.pykubeslurm.jwtKeyResourceName }}
          {{- else }}
          configMap:
            name: {{ .Values.pykubeslurm.jwtKeyResourceName }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - name: jwt-key
              mountPath: {{ .Values.pykubeslurm.config.slurmrestdJwtKeyPath | printf "%s" }}
              {{- if not .Values.pykubeslurm.jwtKeyFromSecret }}
              subPath: {{ .Values.pykubeslurm.config.slurmrestdJwtKeyPath | splitList "/" | last }}
              {{- end }}
              readOnly: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pykubeslurm.config.healthCheckPort }}
              protocol: TCP
          env:
            - name: DEBUG_LEVEL
              value: {{ .Values.pykubeslurm.config.debugLevel }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: EVENT_LISTENER_TIMEOUT
              value: {{ .Values.pykubeslurm.config.eventListenerTimeout }}
            - name: SLURMRESTD_USER_TOKEN
              value: {{ .Values.pykubeslurm.config.slurmrestdUserToken }}
            - name: SLURMRESTD_JWT_KEY_PATH
              value: {{ .Values.pykubeslurm.config.slurmrestdJwtKeyPath }}
            - name: CACHE_DIR
              value: /.pykubeslurm/cache
            - name: SLURMRESTD_TIMEOUT
              value: {{ .Values.pykubeslurm.config.slurmrestdTimeout }}
            - name: SLURMRESTD_ENDPOINT
              value: {{ .Values.pykubeslurm.config.slurmrestdUrl }}
            - name: SLURMRESTD_EXP_TIME_IN_SECONDS
              value: {{ .Values.pykubeslurm.config.slurmrestdExpTime }}
            - name: RECONCILIATION_TIME
              value: {{ .Values.pykubeslurm.config.reconciliationInterval }}
            - name: HEALTH_CHECK_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HEALTH_CHECK_PORT
              value: {{ .Values.pykubeslurm.config.healthCheckPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
