apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: slurmjobs.mhtosta.engineering
spec:
  group: mhtosta.engineering
  names:
    kind: SlurmJob
    listKind: SlurmJobList
    plural: slurmjobs
    singular: slurmjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - script
              properties:
                script:
                  type: string
                account:
                  type: string
                cpus_per_task:
                  type: integer
                  format: int32
                name:
                  type: string
                partition:
                  type: string
                admin_comment:
                  type: string
                allocation_node_list:
                  type: string
                allocation_node_port:
                  type: integer
                  format: int32
                argv:
                  type: array
                  items:
                    type: string
                batch_features:
                  type: string
                begin_time:
                  type: string
                  pattern: '(?:\d{2}:\d{2}(:\d{2})?|midnight|noon|fika|teatime|\d{6}|\d{2}\/\d{2}\/\d{2}|YYYY-MM-DD(?:T\d{2}:\d{2}(:\d{2})?)?|now(?:\s*\+\s*\d+\s*(?:seconds|minutes|hours|hour|days|weeks))?|(?:today|tomorrow))'
                flags:
                  type: array
                  items:
                    type: string
                burst_buffer:
                  type: string
                clusters:
                  type: string
                cluster_constraint:
                  type: string
                comment:
                  type: string
                contiguous:
                  type: boolean
                container:
                  type: string
                container_id:
                  type: string
                core_specification:
                  type: integer
                  format: int32
                thread_specification:
                  type: integer
                  format: int32
                cpu_binding:
                  type: string
                cpu_binding_flags:
                  type: array
                  items:
                    type: string
                cpu_frequency:
                  type: string
                cpus_per_tres:
                  type: string
                crontab:
                  type: string
                deadline:
                  type: integer
                  format: int64
                delay_boot:
                  type: integer
                  format: int32
                dependency:
                  type: string
                end_time:
                  type: integer
                  format: int64
                environment:
                  type: object
                excluded_nodes:
                  type: array
                  items:
                    type: string
                extra:
                  type: string
                constraints:
                  type: string
                group_id:
                  type: string
                hetjob_group:
                  type: integer
                  format: int32
                immediate:
                  type: boolean
                job_id:
                  type: integer
                  format: int32
                kill_on_node_fail:
                  type: boolean
                licenses:
                  type: string
                mail_type:
                  type: array
                  items:
                    type: string
                mcs_label:
                  type: string
                memory_binding:
                  type: string
                memory_binding_type:
                  type: array
                  items:
                    type: string
                memory_per_tres:
                  type: string
                network:
                  type: string
                nice:
                  type: integer
                  format: int32
                tasks:
                  type: integer
                  format: int32
                open_mode:
                  type: array
                  items:
                    type: string
                reserve_ports:
                  type: integer
                  format: int32
                overcommit:
                  type: boolean
                distribution_plane_size:
                  type: integer
                  format: int32
                power_flags:
                  type: array
                  items:
                    type: string
                prefer:
                  type: string
                hold:
                  type: boolean
                priority:
                  type: integer
                  format: int32
                profile:
                  type: array
                  items:
                    type: string
                qos:
                  type: string
                reboot:
                  type: boolean
                requeue:
                  type: boolean
                reservation:
                  type: string
                shared:
                  type: array
                  items:
                    type: string
                exclusive:
                  type: array
                  items:
                    type: string
                oversubscribe:
                  type: boolean
                site_factor:
                  type: integer
                  format: int32
                spank_environment:
                  type: array
                  items:
                    type: string
                distribution:
                  type: string
                time_limit:
                  type: integer
                  format: int32
                time_minimum:
                  type: integer
                  format: int32
                tres_bind:
                  type: string
                tres_freq:
                  type: string
                tres_per_job:
                  type: string
                tres_per_node:
                  type: string
                tres_per_socket:
                  type: string
                tres_per_task:
                  type: string
                user_id:
                  type: string
                wait_all_nodes:
                  type: boolean
                kill_warning_flags:
                  type: array
                  items:
                    type: string
                kill_warning_signal:
                  type: string
                kill_warning_delay:
                  type: integer
                  format: int16
                current_working_directory:
                  type: string
                minimum_cpus:
                  type: integer
                  format: int32
                maximum_cpus:
                  type: integer
                  format: int32
                nodes:
                  type: array
                  items:
                    type: integer
                minimum_nodes:
                  type: integer
                  format: int32
                maximum_nodes:
                  type: integer
                  format: int32
                minimum_boards_per_node:
                  type: integer
                  format: int32
                minimum_sockets_per_board:
                  type: integer
                  format: int32
                sockets_per_node:
                  type: integer
                  format: int32
                threads_per_core:
                  type: integer
                  format: int32
                tasks_per_node:
                  type: integer
                  format: int32
                tasks_per_socket:
                  type: integer
                  format: int32
                tasks_per_core:
                  type: integer
                  format: int32
                tasks_per_board:
                  type: integer
                  format: int32
                ntasks_per_tres:
                  type: integer
                  format: int32
                minimum_cpus_per_node:
                  type: integer
                  format: int32
                memory_per_cpu:
                  type: integer
                  format: uint64
                memory_per_node:
                  type: integer
                  format: uint64
                temporary_disk_per_node:
                  type: integer
                  format: int32
                selinux_context:
                  type: string
                required_switches:
                  type: integer
                  format: uint32
                standard_error:
                  type: string
                standard_input:
                  type: string
                standard_output:
                  type: string
                wait_for_switch:
                  type: integer
                  format: int32
                wckey:
                  type: string
                x11:
                  type: array
                  items:
                    type: string
                x11_magic_cookie:
                  type: string
                x11_target_host:
                  type: string
                x11_target_port:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                slurmJobId:
                  type: integer
                  format: int64
                  nullable: true
                errors:
                  type: array
                  items:
                    type: string
                  nullable: true
                state:
                  type: string
                  enum:
                    - REJECTED
                    - SUBMITTED
                    - FAILED
                    - CANCELLED
                    - COMPLETED
                    - UNKNOWN
                    - PENDING
                    - RUNNING
                updatedAt:
                  type: string
                  format: date-time
                reason:
                  type: string
                  nullable: true
                lastAppliedSpec:
                  type: string
                  nullable: true
          required:
            - spec
