# Configuration for mkdocs
# [Reference](https://github.com/omnivector-solutions/jobbergate/blob/main/jobbergate-docs/docs/mkdocs.yaml)

site_name: PyKubeSlurm Documentation
site_url: https://pykubeslurm.mhtosta.engineering
repo_url: https://github.com/matheushent/PyKubeSlurm
repo_name: matheushent/PyKubeSlurm
docs_dir: source
theme:
  extra_css:
    - 'stylesheets/extra.css'
  name: material
  logo: https://mhtosta-public-assets.s3.sa-east-1.amazonaws.com/PyKubeSlurm.svg
  font:
    code: Fira Code
  features:
    - navigation.expand
    - navigation.footer
    - navigation.tracking
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
watch:
  - ../pykubeslurm
plugins:
  search:
    lang: en
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [..]
        options:
          heading_level: 3
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true
          show_source: false
          docstring_style: google
          show_submodules: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.details:
  - admonition:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md
  - Getting Started:
      - Requirements: getting-started/requirements.md
      - Kubernetes Setup: getting-started/k8s-setup.md
      # - Charmed Kubernetes Setup: getting-started/charmed-k8s.md
  - Deployment:
      - Helm: deployment/helm.md
      # - Charmed K8S: deployment/charmed-k8s.md
      - Deployment Alternatives: deployment/deployment-alternatives.md
  - Usage:
      - Submit job to Slurm: usage/job-submission.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Authors: authors.md
  - Reference:
      - PyKubeSlurm: reference/pykubeslurm.md