# Configuration for mkdocs

site_name: PyKubeSlurm Documentation
repo_url: https://github.com/matheushent/PyKubeSlurm
repo_name: matheushent/PyKubeSlurm
docs_dir: source
theme:
  name: material
  logo: https://mhtosta-public-assets.s3.sa-east-1.amazonaws.com/PyKubeSlurm.svg
  font:
    code: Fira Code
  features:
    - navigation.expand
    - navigation.footer
    - navigation.tracking
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
watch:
  - ../pykubeslurm
plugins:
  search:
    lang: en
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [..]
        options:
          heading_level: 3
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true
          show_source: false
          docstring_style: google
          show_submodules: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.details:
  - admonition:
  - attr_list:
nav:
  - Home: index.md
  - Getting Started:
      - Requirements: getting-started/requirements.md
      - Kubernetes Setup: getting-started/k8s-setup.md
  - Deployment:
      - Helm: deployment/helm.md
      - Charmed K8S: deployment/charmed-k8s.md
      - Deployment Alternatives: deployment/deployment-alternatives.md
  # - Usage:
  # - Elements:
  #     - Resources:
  #         - Overview: elements/resources/index.md
  #         - Job Scripts: elements/resources/job_scripts.md
  #         - Job Script Templates: elements/resources/job_script_templates.md
  #         - Job Submissions: elements/resources/job_submissions.md
  #     - Apps:
  #         - Overview: elements/apps/index.md
  #         - Jobbergate Agent: elements/apps/agent.md
  #         - Jobbergate API: elements/apps/api.md
  #         - Jobbergate CLI: elements/apps/cli.md
  #         - Jobbergate Core: elements/apps/core.md
  # - Tutorial: tutorial.md
  # - Developer Guide:
  #     - Developer Tools: developer_guide/dev_tools.md
  #     - Quality Assurance Tools: developer_guide/qa_tools.md
  #     - Integration Testing: developer_guide/integration_testing.md
  #     - Continuous Integration: developer_guide/ci.md
  #     - Keycloak Setup: developer_guide/keycloak_setup.md
  #     - Template Workflows: developer_guide/template_workflows.md
  - Authors: authors.md
  - Reference:
      - PyKubeSlurm: reference/pykubeslurm.md